#include <QGridLayout>

#include "howtoscoredialog.hpp"

HowToScoreDialog::HowToScoreDialog()
    : left_text_(new QLabel), right_text_(new QLabel),
      ok_button_(new QPushButton(tr("Ok"))) {
    /* Set texts */
    left_text_->setText(QString(tr(
        "<table style=\"width:100%\">"
        "<tr><th align=\"left\"><b>Hand pattern</b></th>"
        "<th align=\"right\"><b>Fu score</b></th></tr>"
        "<tr><td align=\"left\">Base Score</td><td align=\"right\">20</td></tr>"
        "<tr><td align=\"left\">Closed hand won by ron</td><td "
        "align=\"right\">10</td></tr>"
        "<tr><td align=\"left\">Tsumo (not Pinfu)</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Valued wait winning tile</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Pair is player's wind</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Pair is dominant wind</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Pair is dragon</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Melded simple pon</td><td "
        "align=\"right\">2</td></tr>"
        "<tr><td align=\"left\">Concealed simple pon</td><td "
        "align=\"right\">4</td></tr>"
        "<tr><td align=\"left\">Melded major pon</td><td "
        "align=\"right\">4</td></tr>"
        "<tr><td align=\"left\">Concealed major pon</td><td "
        "align=\"right\">8</td></tr>"
        "<tr><td align=\"left\">Melded simple kan</td><td "
        "align=\"right\">8</td></tr>"
        "<tr><td align=\"left\">Concealed simple kan</td><td "
        "align=\"right\">16</td></tr>"
        "<tr><td align=\"left\">Melded major kan</td><td "
        "align=\"right\">16</td></tr>"
        "<tr><td align=\"left\">Concealed major kan</td><td "
        "align=\"right\">32</td></tr>"
        "<tr><td align=\"left\">Seven Pairs</td><td "
        "align=\"right\">always 25</td></tr>"
        "<tr><td align=\"left\">Open Pinfu</td><td "
        "align=\"right\">always rounded to 30</td></tr>"
        "</table><br><br>"
        "<b>Calculating Fan</b><br>"
        "Bonus Fan = Yaku + Dora<br>"
        "<table style=\"width:100%\">"
        "<tr><th align=\"left\"><b>Winner</b></th><th align=\"right\"><b>Pay "
        "Hand's Value</b></th></tr>"
        "<tr><td align=\"left\">Dealer by tsumo</td><td align=\"right\">x2 for "
        "each player</td></tr>"
        "<tr><td align=\"left\">Dealer by ron</td><td align=\"right\">x6 for "
        "discarder</td></tr>"
        "<tr><td align=\"left\">Non-dealer by tsumo &nbsp;&nbsp;</td><td "
        "align=\"right\">x1 "
        "for each non-dealer</td></tr>"
        "<tr><td align=\"left\">Non-dealer by tsumo</td><td align=\"right\">x2 "
        "for the dealer</td></tr>"
        "<tr><td align=\"left\">Non-dealer by ron</td><td align=\"right\">x4 "
        "for discarder</td></tr>"
        "</table>"
        "<br><br><b>Winner collects all riichi wagers</b>")));

    right_text_->setText(QString(
        tr("<table style=\"width:100%\">"
           "<tr><th align=\"left\"><b>Yaku</b></th>"
           "<th align=\"right\"><b>Fan closed/open</b></th></tr>"
           "<tr><td align=\"left\">Riichi</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Double Riichi</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Ippatsu (one-shot riichi)</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Open Riichi</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Pinfu Hand</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Fully Concealed Hand</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Double Chii</td><td "
           "align=\"right\">1/0</td></tr>"
           "<tr><td align=\"left\">Seven Unique Pairs</td><td "
           "align=\"right\">2/0</td></tr>"
           "<tr><td align=\"left\">Twice Double Chii</td><td "
           "align=\"right\">total 3/0</td></tr>"
           "<tr><td align=\"left\">All Simples</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Dragon Pon</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Player's Wind Pon</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Prevailing Wind Pon</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Last Tile Win</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Supplemental Tile Win</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Rob a Kan</td><td "
           "align=\"right\">1/1</td></tr>"
           "<tr><td align=\"left\">Three Suit Chii</td><td "
           "align=\"right\">2/1</td></tr>"
           "<tr><td align=\"left\">Pure Straight</td><td "
           "align=\"right\">2/1</td></tr>"
           "<tr><td align=\"left\">All Pon Hand</td><td "
           "align=\"right\">2/2</td></tr>"
           "<tr><td align=\"left\">Three Suit Pon</td><td "
           "align=\"right\">2/2</td></tr>"
           "<tr><td align=\"left\">Three Concealed Pon</td><td "
           "align=\"right\">2/2</td></tr>"
           "<tr><td align=\"left\">Three Kan</td><td "
           "align=\"right\">2/2</td></tr>"
           "<tr><td align=\"left\">All Terminals and Honors Hand</td><td "
           "align=\"right\">2/2</td></tr>"
           "<tr><td align=\"left\">Mixed Outside Hand</td><td "
           "align=\"right\">2/1</td></tr>"
           "<tr><td align=\"left\">Pure Outside Hand</td><td "
           "align=\"right\">3/2</td></tr>"
           "<tr><td align=\"left\">Half Flush Hand</td><td "
           "align=\"right\">3/2</td></tr>"
           "<tr><td align=\"left\">Full Flush Hand</td><td "
           "align=\"right\">6/5</td></tr>"
           "<tr><td align=\"left\">Little Three Dragons</td><td "
           "align=\"right\">total 4/4</td></tr>"
           "<tr><td align=\"left\">Hand of Man</td><td "
           "align=\"right\">mangan</td></tr>"
           "<tr><td align=\"left\">Nagashi Mangan</td><td "
           "align=\"right\">mangan</td></tr>"
           "<tr><td align=\"left\">Four Kans</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Nine Gates</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">All Green Hand</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">All Terminals Hand</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Big Three Dragons</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Little Four Winds</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Big Four Winds</td><td "
           "align=\"right\">2 yakuman</td></tr>"
           "<tr><td align=\"left\">All Honours Hand</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Seven Honor Pairs</td><td "
           "align=\"right\">2 yakuman</td></tr>"
           "<tr><td align=\"left\">Thirteen Orphans</td><td "
           "align=\"right\">2 yakuman</td></tr>"
           "<tr><td align=\"left\">Earthly Hand</td><td "
           "align=\"right\">yakuman</td></tr>"
           "<tr><td align=\"left\">Heavenly Hand</td><td "
           "align=\"right\">yakuman</td></tr>"
           "</table>")));

    /* Connect OK button with exit */
    connect(ok_button_, &QPushButton::clicked, this, &HowToScoreDialog::reject);

    /* Define Layout */
    QGridLayout *layout = new QGridLayout;
    layout->addWidget(left_text_, 0, 0, 1, 2);
    layout->setAlignment(left_text_, Qt::AlignTop);
    layout->addWidget(right_text_, 0, 2, 1, 2);
    layout->setAlignment(right_text_, Qt::AlignTop);
    layout->addWidget(ok_button_, 1, 1, 1, 2);

    setLayout(layout);
}